---
# This is a role for setting up the client.

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'


- name: Update apt cache
  apt:
    update_cache: yes

- name: Set executable permission for xstartup
  file:
    path: ~/.vnc/xstartup
    mode: '+x'

- name: Create script file
  copy:
    src: basic_auth.sh
    dest: /opt/basic_auth.sh
    mode: "0755"

...
